---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: macos-10.12

suites:
<% %w(12 13 14).each do |version| %>
  - name: two-sample-apps_chef-<%= version %>
    provisioner:
      require_chef_omnibus: <%= version %>
    run_list:
      - recipe[mac-app-store]
    attributes:
      mac_app_store:
        username: <%= ENV['APPLE_ID_USERNAME'] %>
        password: <%= ENV['APPLE_ID_PASSWORD'] %>
        apps:
          Microsoft Remote Desktop: true
          White Noise Free: true
<% end %>
