---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: macosx-10.9
    driver:
      box: opscode-macosx-10.9
      ssh:
        insert_key: false

suites:
  - name: two-sample-apps
    run_list:
      - recipe[mac-app-store]
    attributes:
      mac_app_store:
        username: <%= ENV['APPLE_ID_USERNAME'] %>
        password: <%= ENV['APPLE_ID_PASSWORD'] %>
        apps:
          - Microsoft Remote Desktop
          - White Noise Lite
