---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: macosx-10.9
    driver:
      ssh:
        insert_key: false

suites:
  - name: default
    run_list:
      - recipe[mac-app-store]
    attributes:
      mac_app_store:
        apps:
          Microsoft Remote Desktop: com.microsoft.rdc.mac
          White Noise Lite: com.tmsoft.mac.WhiteNoiseLite
# TODO:
# - name: app_not_purchased
# - name: user_not_signed_in
