---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: macos-10.12

suites:
  - name: two-sample-apps
    run_list:
      - recipe[mac-app-store]
    attributes:
      mac_app_store:
        username: <%= ENV['APPLE_ID_USERNAME'] %>
        password: <%= ENV['APPLE_ID_PASSWORD'] %>
        apps:
          Microsoft Remote Desktop: true
          White Noise Free: true
        mas:
          version: 1.3.1
